# sops.yaml
creation_rules:
  - gcp_kms: projects/peppy-ward-443601-i7/locations/northamerica-northeast1/keyRings/my-keyring/cryptoKeys/my-key
    # Specify any file patterns you want to auto-encrypt
    path_regex: '.*\.yaml$'
    encrypted_regex: '^(secrets)$'
