wp:
    secrets:
        WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:lhK0UBSR8w9H,iv:NX4aLs29Q43XuoO/7S9gSJ2WMFpDFXx/EtaWMyTqYFE=,tag:mI5nEBlwcsnlaTaFPj4bXA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/peppy-ward-443601-i7/locations/northamerica-northeast1/keyRings/my-keyring/cryptoKeys/my-key
          created_at: "2024-12-04T15:06:44Z"
          enc: CiQA1Yh9OArT9jHiUmrC0QjR/q3JSDZaUeJVxsje7IlCG+L6CUoSSQAvaFsf9MaVt8we3gdidvgVVWdduyuznM7xnxwQaQ0i+/rFc7O2eNokdKLlyJbPJp+aIZ674ZyqYEIv4sTfrYBGBHfAphRFd7Y=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-04T15:06:45Z"
    mac: ENC[AES256_GCM,data:++WzJpolJI6X17x7kIjOqa7kKSh/dTyPkztrAEMpiJh7JEQAFUPjIf8+wIZ7fj1pgM5fPiv9wlbJbBSBBS6GfLt3OxB3IaSI0JjZCR9QQ7BQpQdYZHfwq3gL4PhJM2bmXHfIP0Pd2lNFMtS3mBf6p4cmfIHsO6i/nYF7sXVYCzs=,iv:P5H3SH7DW5NFdDnyWFKeYbz9Q68w9cSq3qm/z+TvFqo=,tag:OodSPImh15w1zzmh9tKA0A==,type:str]
    pgp: []
    encrypted_regex: ^(secrets)$
    version: 3.9.1
