---
# Source: wordpress-proxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wp-proxy-service
  labels:
    app: wp-proxy-app
    env: dev
    id: c0903980
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wp-proxy-app
    env: dev
    id: c0903980
